---
changelog:
  exclude:
    authors:
      - Copilot
      - copilot-swe-agent[bot]
      - dependabot[bot]
      - gemini-code-assist[bot]
      - github-actions[bot]
      - pre-commit-ci[bot]
      - renovate[bot]
      - snyk-bot
