---
default: true
first-line-heading: false
line-length: false
no-duplicate-heading:
  siblings_only: true
table-column-style:
  style: compact
ul-style:
  style: dash
no-inline-html:
  allowed_elements:
    - br
    - details
    - summary
