#!/usr/bin/env bash

set -euo pipefail

SCRIPT_NAME=$(basename "$0")

usage() {
  cat << EOF
Usage: $SCRIPT_NAME [-h|--help]

Update the Unreleased section of CHANGELOG.md using git cliff.

This script runs 'git cliff --unreleased' to generate fresh changelog content,
then replaces the existing ## [Unreleased] section in CHANGELOG.md with the
newly generated content.

The '<!-- generated by git-cliff -->' comment is automatically excluded.

Options:
  -h, --help    Show this help message and exit.

Examples:
  $SCRIPT_NAME              # Update CHANGELOG.md with fresh unreleased content
  $SCRIPT_NAME --help       # Show this help message

Requirements:
  - git cliff must be installed and available in PATH
  - Must be run from a git repository with a cliff.toml configuration
  - CHANGELOG.md must exist with an existing ## [Unreleased] section
EOF
  exit "${1:-0}"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h | --help)
      usage 0
      ;;
    *)
      echo "Error: Unknown option: $1" >&2
      usage 1
      ;;
  esac
done

CHANGELOG="CHANGELOG.md"
TEMP_FILE=$(mktemp)
CLIFF_OUTPUT=$(mktemp)

# Generate unreleased changes with git cliff
git cliff --unreleased > "$CLIFF_OUTPUT"

# Extract the Unreleased section from git cliff output:
# - Start from "## [Unreleased]"
# - End before the next "## [" or "<!-- generated by git-cliff -->"
# - Exclude the git-cliff generated comment
awk '
  /^## \[Unreleased\]/ { in_unreleased = 1 }
  in_unreleased && /^<!-- generated by git-cliff -->/ { exit }
  in_unreleased && /^## \[/ && !/^## \[Unreleased\]/ { exit }
  in_unreleased { print }
' "$CLIFF_OUTPUT" > "$TEMP_FILE"

# Check if we got valid content
if [ ! -s "$TEMP_FILE" ]; then
  echo "Error: No Unreleased section found in git cliff output" >&2
  rm -f "$TEMP_FILE" "$CLIFF_OUTPUT"
  exit 1
fi

# Remove trailing blank lines from the extracted section
# but ensure it ends with exactly one newline
sed -i.bak -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$TEMP_FILE" 2> /dev/null || # spellchecker:disable-line
  sed -i '' -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$TEMP_FILE"                # spellchecker:disable-line
rm -f "${TEMP_FILE}.bak"

# Now replace the Unreleased section in CHANGELOG.md
# We need to:
# 1. Keep everything before "## [Unreleased]"
# 2. Insert the new Unreleased content
# 3. Keep everything from the next "## [" section onwards

awk -v new_content="$TEMP_FILE" '
  BEGIN { in_unreleased = 0; printed_new = 0 }

  # When we hit the Unreleased header, start skipping
  /^## \[Unreleased\]/ {
    in_unreleased = 1
    # Print the new content
    while ((getline line < new_content) > 0) {
      print line
    }
    close(new_content)
    printed_new = 1
    next
  }

  # When we hit the next version section, stop skipping
  in_unreleased && /^## \[/ && !/^## \[Unreleased\]/ {
    in_unreleased = 0
    # Ensure blank line before next section
    print ""
    print
    next
  }

  # Skip lines while in the old Unreleased section
  in_unreleased { next }

  # Print all other lines
  { print }
' "$CHANGELOG" > "${CHANGELOG}.new"

# Replace the original file
mv "${CHANGELOG}.new" "$CHANGELOG"

# Cleanup
rm -f "$TEMP_FILE" "$CLIFF_OUTPUT"

echo "Successfully updated Unreleased section in $CHANGELOG"
